version: '3'

services:
  rails:
    expose:
      - 3000

  postgres:
    image: postgres:12
    volumes:
      - /data/postgres:/var/lib/postgresql/data

  nginx-chatwoot:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    container_name: nginx-chatwoot
    depends_on:
      - rails
    ports:
      - '0.0.0.0:443:443'
